-- Seed full product catalog (skip names that already exist, e.g. Guji)
insert into public.products (name, description, price, category, image_url, display_order)
select v.name, v.description, v.price, v.category, v.image_url, v.display_order
from (values
  ('Yirgacheffe', E'Coffee Details\n\n* Acidity: Bright\n* Sweetness: Medium\n* Body: Silky\n\nFlavor profile: Citrus and floral\n\nMore Information\n\n* Origin: Ethiopia\n* Region: Yirgacheffe\n* Processing Method: Washed\n* Tasting Notes: Bergamot – Lemon – Honey – Floral\n* Rating: 88\n* Altitude: 1,900–2,200 m\n* Variety: Heirloom\n\nRoaster''s Description\n\n“Elegant and aromatic — a landmark Ethiopian cup with sparkling citrus and a clean floral finish. Ideal for pour-over.”', 85::numeric, 'coffee-beans', 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=800', 1),
  ('Colombia', E'Coffee Details\n\n* Acidity: Medium\n* Sweetness: High\n* Body: Medium-full\n\nFlavor profile: Sweet and balanced\n\nMore Information\n\n* Origin: Colombia\n* Region: Huila\n* Processing Method: Washed\n* Tasting Notes: Caramel – Red Apple – Cocoa – Nut\n* Rating: 85\n* Altitude: 1,500–1,900 m\n* Variety: Caturra / Castillo\n\nRoaster''s Description\n\n“A classic balanced Colombian roast — caramel sweetness with soft fruit and a comforting cocoa finish. Excellent daily drinker.”', 70, 'coffee-beans', 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&q=80&w=800', 2),
  ('Brazil Cerrado', E'Coffee Details\n\n* Acidity: Low\n* Sweetness: High\n* Body: Creamy\n\nFlavor profile: Nutty chocolate\n\nMore Information\n\n* Origin: Brazil\n* Region: Cerrado Mineiro\n* Processing Method: Natural\n* Tasting Notes: Chocolate – Hazelnut – Brown Sugar\n* Rating: 84\n* Altitude: 900–1,200 m\n* Variety: Yellow Bourbon\n\nRoaster''s Description\n\n“Smooth and chocolate-forward with low acidity — perfect for espresso, milk drinks, and anyone who prefers a richer cup.”', 65, 'coffee-beans', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800', 3),
  ('Kenya AA', E'Coffee Details\n\n* Acidity: High\n* Sweetness: Medium\n* Body: Juicy\n\nFlavor profile: Bold berry and citrus\n\nMore Information\n\n* Origin: Kenya\n* Region: Nyeri\n* Processing Method: Washed\n* Tasting Notes: Blackcurrant – Tomato – Grapefruit – Brown Sugar\n* Rating: 89\n* Altitude: 1,700–1,900 m\n* Variety: SL28 / SL34\n\nRoaster''s Description\n\n“Vibrant and complex Kenyan AA with signature blackcurrant brightness. Best as filter for those who love lively acidity.”', 90, 'coffee-beans', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800', 4),
  ('Signature Drip Box', E'Ready-to-brew drip bags with our house blend.\n\n* Pack: 10 sachets\n* Roast: Medium\n* Brew time: ~3 minutes\n* Tasting Notes: Honey – Orange – Soft Cocoa\n\nNo equipment needed — just hot water and a mug.', 45, 'drip-coffee', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800', 0),
  ('Dark Roast Drip Box', E'Bold single-serve drip bags for a deeper cup.\n\n* Pack: 10 sachets\n* Roast: Dark\n* Brew time: ~3 minutes\n* Tasting Notes: Dark Chocolate – Molasses – Smoke\n\nRich and comforting.', 45, 'drip-coffee', 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&q=80&w=800', 1),
  ('Ethiopia Drip Pack', E'Light-roast Ethiopian drip bags.\n\n* Pack: 8 sachets\n* Roast: Light\n* Origin: Ethiopia\n* Tasting Notes: Jasmine – Peach – Bergamot', 52, 'drip-coffee', 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&q=80&w=800', 2),
  ('Colombia Drip Pack', E'Sweet Colombian drip sachets.\n\n* Pack: 8 sachets\n* Roast: Medium\n* Origin: Colombia\n* Tasting Notes: Caramel – Apple – Cocoa', 48, 'drip-coffee', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=800', 3),
  ('Pour-Over Kettle', E'Gooseneck stainless-steel kettle.\n\n* Capacity: 1.0 L\n* Material: Brushed stainless steel', 180, 'essentials', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=800', 0),
  ('Manual Coffee Grinder', E'Hand grinder with adjustable ceramic burrs.\n\n* Burrs: Ceramic conical\n* Grind range: Fine → coarse', 140, 'essentials', 'https://images.unsplash.com/photo-1610889556528-9a770639fc2b?auto=format&fit=crop&q=80&w=800', 1),
  ('Ceramic Pour-Over Dripper', E'V-shaped ceramic dripper.\n\n* Size: 1–2 cups\n* Material: Glazed ceramic', 95, 'essentials', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&q=80&w=800', 2),
  ('Brew Scale', E'Compact digital scale with 0.1 g precision.\n\n* Precision: 0.1 g\n* Capacity: 2 kg', 120, 'essentials', 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&q=80&w=800', 3),
  ('Paper Filters (100 pcs)', E'Oxygen-bleached cone filters.\n\n* Count: 100 filters\n* Shape: Cone / V60-compatible', 25, 'essentials', 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&q=80&w=800', 4)
) as v(name, description, price, category, image_url, display_order)
where not exists (
  select 1 from public.products p where lower(p.name) = lower(v.name)
);
